[Webhook]
url = "My Webhook URL"

[Base]
username = "My User Name"
avatar_url = "My avatar URL"

[Message]
content = "Hello World in $TIME_NOW"

[[Embeds]]
title = "Hello world with my customize variable $TIME_NOW"
description = "Same now: $TIME_NOW"

[Embeds.footer]
text = "Same now: $TIME_NOW"
