# Webhook URL is required.
[Webhook]
# For more information, how to get Discord webhook URL, please visit
# https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks
url = "My Discord Webhook URL"

# Base information setup for webhook
[Base]
username = ""   # Your webhook username. Leave blank for default username
avatar_url = "" # Your webhook avatar. Leave blank for default avatar

# Webhook simple content. With no embeds.
[Message]
content = "Hello World. From GoHook !" # Your first content. Awesome!
